name: Build Piaros
on:
  workflow_dispatch:
  pull_request:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - uses: docker/build-push-action@v5
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: BUILDER_TAG=x86_64-musl 
          platforms: linux/amd64

      #- uses: actions/upload-artifact@v4
      #  with:
      #    name: piaros-build
      #    path: piaros-*.tar