name: Build Piaros
on:
  workflow_dispatch:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - shell: bash
        run: ./build.sh

      - uses: actions/upload-artifact@v4
        with:
          name: piaros-container
          path: piaros-*.tar