name: Build Piaros
on:
  workflow_dispatch:
  pull_request:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            builder: x86_64-musl
            platform: linux/amd64
          - arch: arm64
            builder: aarch64-musl
            platform: linux/arm64
          - arch: arm
            builder: armv7-musleabihf
            platform: linux/arm/v7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: suffix=${{ matrix.arch }},onlatest=true

      - id: build
        uses: docker/build-push-action@v5
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: BUILDER_TAG=${{ matrix.builder }}
          platforms: ${{ matrix.platform }}

      - run: docker image save ${{ steps.build.outputs.imageid }} -o piaros-${{ matrix.arch }}.tar

      - uses: actions/upload-artifact@v4
        with:
          name: piaros-${{ matrix.arch }}
          path: piaros-*.tar